### ISSUE TITLE
QGroundControl no longer connects to PX4 SITL running with Gazebo

### ISSUE THREAD

**Issue by lukvacek** [Open-UAV/Firmware#1]
Using the old firmware, it was possible to open QGroundControl and connect to Gazebo/PX4 over the network to send waypoints, change parameters, etc. QGroundControl no longer does that automatically with the new SITL firmware.

**Comment by darknight-007** [comment]
Works if I set gcs_url:="udp://@localhost" . Initially, I started by setting the IP of my laptop on the network, then found out that setting any IP seemed to work...
