### ISSUE TITLE
Flight logs 

### ISSUE THREAD

**Issue by darknight-007** [Open-UAV/Firmware#4]
Record bagfiles of UAVs (state, local_position/odom, imu/data, and relevant setpoint messages for now). Develop mechanism for download.

**Comment by schmittlema** [comment]
https://github.com/darknight-007/Firmware/commit/fdb95bb5ead8f40686508f9d577542330314464f
This records to ~/.ros/
More topics can be added if need be

**Comment by darknight-007** [comment]
Tested ~/.ros/rootfs/fs/microsd/log/

Will verify on flightplot app and expose as a downloadable link on frontend simulation portal.
